//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTRUC_REPORT_CONTROLESRTF
    {
        public string CS_TIPODOC { get; set; }
        public string CS_NUMEROCONTROL { get; set; }
        public string CS_DESCRIPCION { get; set; }
        public string CS_CADENACONTROL { get; set; }
    }
}
