//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTRUC_REPORT
    {
        public string Relacion { get; set; }
        public string tiporel { get; set; }
        public string Clave { get; set; }
        public string texto { get; set; }
        public string imagen { get; set; }
        public string tag { get; set; }
        public string ruta { get; set; }
        public bool seimprime { get; set; }
        public int id { get; set; }
        public string orden { get; set; }
        public int ordenar { get; set; }
        public int replaceone { get; set; }
        public int ENCABEZADO { get; set; }
        public int distribuyeenhoja { get; set; }
    }
}
