//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTRUCT_IMAGEN
    {
        public string cs_key { get; set; }
        public byte[] is_imagen { get; set; }
        public string cs_tipo { get; set; }
        public int ns_tamanoV { get; set; }
        public int ns_tamanoH { get; set; }
        public int ns_Estatus { get; set; }
    }
}
