//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ALERTAGRID_ALERTAS
    {
        public string c_Alerta { get; set; }
        public string c_Descripcion_Evento { get; set; }
        public decimal n_ColorLineaGrid { get; set; }
        public int c_D_E_ResourceID { get; set; }
    }
}
