//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_BANCO_CONFIG
    {
        public double n_MONTOMAX { get; set; }
        public double n_DEBITOBAN { get; set; }
        public double n_DIF_MBAN { get; set; }
        public double n_DIF_PBAN { get; set; }
        public double n_DIF_OPBAN { get; set; }
    }
}
