//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_BANCOREG_X_CXP_CXC
    {
        public string banco_c_concepto { get; set; }
        public string banco_c_documentoInt { get; set; }
        public string banco_c_localidad { get; set; }
        public string Cx_c_documento { get; set; }
        public string Cx_c_concepto { get; set; }
        public string Cx_c_codigo { get; set; }
        public string Cx_cs_codlocalidad { get; set; }
        public bool bu_CxP_CxC { get; set; }
        public string BANCO_C_DOCUMENTO { get; set; }
    }
}
