//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_BANCO_REG
    {
        public decimal id { get; set; }
        public string c_CODBANCO { get; set; }
        public string C_ncuenta { get; set; }
        public string C_codBen { get; set; }
        public string c_nombrebeneficiario { get; set; }
        public string c_descripcion { get; set; }
        public string C_documento { get; set; }
        public string c_concepto { get; set; }
        public string c_observacion { get; set; }
        public string c_documentoInt { get; set; }
        public string c_conciliacion { get; set; }
        public double N_OPERACION { get; set; }
        public double N_monto { get; set; }
        public double n_cliente_prove { get; set; }
        public double n_saldoact { get; set; }
        public System.DateTime f_fechaE { get; set; }
        public System.DateTime F_fechaL { get; set; }
        public Nullable<System.DateTime> F_fechaAplicacion { get; set; }
        public bool b_Anulado { get; set; }
        public bool b_refleja { get; set; }
        public bool b_Ultima_opera { get; set; }
        public bool B_APLICADO { get; set; }
        public bool b_detalla_dep { get; set; }
        public bool b_conciliado { get; set; }
        public string c_localidad { get; set; }
        public string c_TransCuentaHabiente { get; set; }
        public string c_TransCuenta { get; set; }
        public string c_Transcodbanco { get; set; }
        public decimal codconcepto { get; set; }
        public string CU_DOCUMENTO { get; set; }
        public string CU_ORIGEN { get; set; }
        public string CU_ORIGEN_CORRELATIVO { get; set; }
        public int CU_SEIMPRIMIO { get; set; }
        public string CU_TIPO_DOCUMENTO { get; set; }
        public double N_IDB { get; set; }
        public int bu_transferencia { get; set; }
        public string C_USUARIO { get; set; }
        public double n_factor { get; set; }
        public string cs_comprobanteContable { get; set; }
        public System.DateTime ds_fechaEntregado { get; set; }
        public string cu_receptor_cedula { get; set; }
        public string cu_receptor_Descripcion { get; set; }
        public string CS_NUMERO_TRANSFERENCIA { get; set; }
        public string cs_documentoOriginaMov { get; set; }
        public string CS_NUMTRANSF_DESTINO { get; set; }
        public string c_CodMoneda { get; set; }
        public double n_FactorCambio { get; set; }
    }
}
