//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_BANCO_CONCILIA
    {
        public int id { get; set; }
        public string c_codbanco { get; set; }
        public string c_ncuenta { get; set; }
        public double N_conciliado { get; set; }
        public double n_conciliadolibro { get; set; }
        public System.DateTime f_fechac { get; set; }
        public int ano { get; set; }
        public int mes { get; set; }
        public string c_conciliacion { get; set; }
        public double n_Cantidad_nd { get; set; }
        public double n_monto_nd { get; set; }
        public double n_Cantidad_nc { get; set; }
        public double n_monto_nc { get; set; }
        public double n_Cantidad_dep { get; set; }
        public double n_monto_dep { get; set; }
        public double n_Cantidad_che { get; set; }
        public double n_monto_che { get; set; }
        public double n_t_Cantidad_nd { get; set; }
        public double n_t_monto_nd { get; set; }
        public double n_t_Cantidad_nc { get; set; }
        public double n_t_monto_nc { get; set; }
        public double n_t_Cantidad_dep { get; set; }
        public double n_t_monto_dep { get; set; }
        public double n_t_Cantidad_che { get; set; }
        public double n_t_monto_che { get; set; }
        public double N_SALDO { get; set; }
    }
}
