//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_banco_registros
    {
        public string C_CodBanco { get; set; }
        public string C_Codcuenta { get; set; }
        public double n_saldo { get; set; }
        public double n_creditos { get; set; }
        public double n_debitos { get; set; }
        public decimal ID { get; set; }
    }
}
