//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_BANCOS_DENOMINA_COMISION
    {
        public string cs_banco { get; set; }
        public string cs_denomina { get; set; }
        public string ns_porcentaje { get; set; }
        public decimal ns_concepto { get; set; }
        public string ns_PorcOtroBanco { get; set; }
    }
}
