//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_BALANZAS
    {
        public string C_CODIGO { get; set; }
        public string C_DESCRIPCION { get; set; }
        public int C_PREFIJO { get; set; }
        public double N_CONSECUTIVO { get; set; }
        public string C_MARCA { get; set; }
        public int id { get; set; }
    }
}
