//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_BANCOSCTA
    {
        public string c_CUENTA { get; set; }
        public string c_BANCO { get; set; }
        public string c_SUCURSAL { get; set; }
        public string c_DIRECCION { get; set; }
        public string c_GERENTE { get; set; }
        public string c_TELEFONOS { get; set; }
        public string c_FAX { get; set; }
        public string c_EMAIL { get; set; }
        public string c_CONTABLE { get; set; }
        public double n_saldo { get; set; }
        public double n_saldoant { get; set; }
        public double n_saldoconciliado { get; set; }
        public double n_saldoconciliadoant { get; set; }
        public string c_codmoneda { get; set; }
        public string c_consecu_cheque { get; set; }
        public string c_ubicacion_rtf { get; set; }
        public decimal ID { get; set; }
        public double n_conciliado { get; set; }
        public int nu_nivel { get; set; }
        public string cu_tipoArchivoConciliacion { get; set; }
        public string cu_separadorArchivoConciliacion { get; set; }
    }
}
