//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CONCILIACIONAUTO_TEXTOBANCOCONCILIADO
    {
        public string codigoBanco { get; set; }
        public double montoBanco { get; set; }
        public System.DateTime fechaBanco { get; set; }
        public string codigoStellar { get; set; }
    }
}
