//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CONVENIOS_DESCUENTOS
    {
        public string cu_codigoProveedor { get; set; }
        public int nu_tipo { get; set; }
        public string cu_clave { get; set; }
        public string cu_ident { get; set; }
        public string cu_codigoDescuento { get; set; }
    }
}
