//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CAMBIOCODIGO
    {
        public string c_Historico { get; set; }
        public System.DateTime f_Fecha { get; set; }
        public string c_TipoReg { get; set; }
        public string c_CodAfectado { get; set; }
        public string c_Usuario { get; set; }
        public string c_CodStellar { get; set; }
    }
}
