//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CORRELATIVOS
    {
        public string cu_Campo { get; set; }
        public string cu_Descripcion { get; set; }
        public decimal nu_Valor { get; set; }
        public string cu_Formato { get; set; }
    }
}
