//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_configuracion_cambios
    {
        public string cs_documento { get; set; }
        public string cs_ruta { get; set; }
        public bool bs_rtf { get; set; }
        public double nu_cambiomax { get; set; }
        public double nu_cambiomin { get; set; }
        public double nu_antiguedadmin { get; set; }
        public double nu_acummin { get; set; }
        public double nu_valorpuntocargo { get; set; }
        public Nullable<double> nu_valorpuntodescargo { get; set; }
        public Nullable<int> nu_tipopremio { get; set; }
        public int nu_porcprodcambiar { get; set; }
    }
}
