//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CONS_PRECIOS
    {
        public string C_DOCUMENTO { get; set; }
        public string C_CODPROVEEDOR { get; set; }
        public string C_DESCRIPCION { get; set; }
        public string C_CODLOCALIDAD { get; set; }
        public System.DateTime D_FECHA { get; set; }
        public string C_CONCEPTO { get; set; }
        public string C_USUARIO { get; set; }
        public string C_OBSERVACION { get; set; }
        public string C_STATUS { get; set; }
        public string C_RELACION { get; set; }
        public string c_CodMoneda { get; set; }
        public double n_FactorCambio { get; set; }
    }
}
