//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CLIENTES_DATOS_AUX
    {
        public string cs_codigo { get; set; }
        public int ns_tipocuenta { get; set; }
        public int ns_tienetarjeta { get; set; }
        public int ns_vacacion { get; set; }
        public int ns_tipotarjeta { get; set; }
        public int ns_tipoingreso { get; set; }
        public int ns_sexo { get; set; }
        public int ns_carro { get; set; }
        public int ns_computador { get; set; }
        public int ns_comprainternet { get; set; }
        public int ns_mascota { get; set; }
        public int ns_profesion { get; set; }
        public int ns_cable { get; set; }
        public string cs_banco { get; set; }
        public string cs_OtroHobbie { get; set; }
        public string cs_tipomascota { get; set; }
        public string cs_tipocable { get; set; }
        public string cs_profesion { get; set; }
        public int ns_estadocivil { get; set; }
        public string cs_otroestado { get; set; }
        public int ns_Musica { get; set; }
        public int ns_Arte { get; set; }
        public int ns_Cine { get; set; }
        public string cs_TipoDeporte { get; set; }
        public int ns_futbol { get; set; }
        public int ns_beisbol { get; set; }
        public int ns_voleibol { get; set; }
        public int ns_natacion { get; set; }
        public int ns_basquetbol { get; set; }
        public int ns_otrodeporte { get; set; }
        public int ns_cocinar { get; set; }
        public int ns_decorar { get; set; }
        public int ns_leer { get; set; }
        public int ns_manualidades { get; set; }
        public int ns_otrohobbie { get; set; }
        public int ns_paella { get; set; }
        public int ns_aves { get; set; }
        public int ns_mariscos { get; set; }
        public int ns_pastas { get; set; }
        public int ns_carnes { get; set; }
        public int ns_vegetariana { get; set; }
        public int ns_ligera { get; set; }
        public int ns_cerveza { get; set; }
        public int ns_vino { get; set; }
        public int ns_whisky { get; set; }
        public int ns_ron { get; set; }
        public int ns_otrabebida { get; set; }
    }
}
