//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CHEQUERAS
    {
        public decimal IDChequera { get; set; }
        public string c_BANCO { get; set; }
        public string c_CUENTA { get; set; }
        public decimal NumDesde { get; set; }
        public decimal NumHasta { get; set; }
        public decimal Cantidad { get; set; }
        public string Estado { get; set; }
    }
}
