//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CIERRECAJA
    {
        public string CodUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public double Monto { get; set; }
        public double MontoFondo { get; set; }
        public bool Cerrada { get; set; }
        public decimal ID { get; set; }
    }
}
