//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CONCILIACIONAUTO_CAMBIOARCHIVO
    {
        public string codigoBanco { get; set; }
        public string codigoCuenta { get; set; }
        public string nombreCampo { get; set; }
        public string tipoCampo { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
    }
}
