//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_COMPARATIVO_PRECIOS
    {
        public string c_codigo { get; set; }
        public System.DateTime d_Fecha { get; set; }
        public string TipoPrecio { get; set; }
        public string status { get; set; }
        public string Observacion { get; set; }
        public string Descripcion { get; set; }
    }
}
