//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_COMPETIDORES
    {
        public string C_codigo { get; set; }
        public string Rif { get; set; }
        public string Descripcion { get; set; }
        public string RazonSocial { get; set; }
        public string Localidad { get; set; }
        public string Observacion { get; set; }
        public string Status { get; set; }
        public string Alias { get; set; }
    }
}
