//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CONCILIACIONAUTO_TEMPORAL
    {
        public string codigoTransaccion { get; set; }
        public string detalleTransaccion { get; set; }
        public string numeroTransaccion { get; set; }
        public double montoTransaccion { get; set; }
        public System.DateTime fechaTransaccion { get; set; }
        public string tipoTransaccion { get; set; }
    }
}
