//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CXC_DETPAG
    {
        public string C_CONCEPTO { get; set; }
        public string C_DOCUMENTO { get; set; }
        public string C_CODMONEDA { get; set; }
        public string C_CODDENOMINA { get; set; }
        public string C_CODBANCO { get; set; }
        public string C_NUM_CHEQUE { get; set; }
        public System.DateTime F_FECHA { get; set; }
        public double N_MONTO { get; set; }
        public double N_FACTOR { get; set; }
        public double N_CANTIDAD { get; set; }
        public double N_VUELTO { get; set; }
        public double n_declarado { get; set; }
        public string c_Tr_Documento_Rel { get; set; }
        public decimal id { get; set; }
        public string cs_codlocalidad { get; set; }
    }
}
