//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CAMBIOS_PREMIOS_CONSOLIDADOS
    {
        public string cs_codigocliente { get; set; }
        public System.DateTime ds_fechacambio { get; set; }
        public string cs_documento { get; set; }
        public string cs_usuario { get; set; }
        public string cs_tipo { get; set; }
        public double nu_puntos { get; set; }
        public string cs_sucursal { get; set; }
        public string cs_rif { get; set; }
        public string cs_numero_bajada { get; set; }
        public Nullable<System.DateTime> ds_fecha { get; set; }
    }
}
