//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CATALOGO_PREMIOS
    {
        public string cs_codigo { get; set; }
        public Nullable<System.DateTime> ds_fechahora_inicio { get; set; }
        public Nullable<System.DateTime> ds_fechahora_fin { get; set; }
        public bool bs_tipopremio { get; set; }
        public bool bs_producto { get; set; }
        public decimal ns_valor { get; set; }
        public string cs_descripcion { get; set; }
    }
}
