//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Consecutivos
    {
        public decimal Solicitud_Precio { get; set; }
        public decimal espera_sdp { get; set; }
        public decimal Orden_Compra { get; set; }
        public decimal espera_odc { get; set; }
        public decimal Compras { get; set; }
        public decimal espera_com { get; set; }
        public decimal cons_precios { get; set; }
        public decimal cons_precios_esp { get; set; }
        public decimal DEVCOMPRAS { get; set; }
        public decimal DEVCOMPRAS_ESP { get; set; }
        public decimal cod_proveedor { get; set; }
        public decimal Recepcion { get; set; }
        public decimal rec_espera { get; set; }
        public decimal rec_anular { get; set; }
        public decimal Transferencia { get; set; }
        public decimal espera_transfer { get; set; }
        public decimal TRANSFERENCIA_ANU { get; set; }
        public decimal Traslados { get; set; }
        public decimal espera_traslado { get; set; }
        public decimal TRASLADOS_ANU { get; set; }
        public decimal Ajustes { get; set; }
        public decimal ESPERA_AJU { get; set; }
        public decimal ajuste_anu { get; set; }
        public decimal Invfisico { get; set; }
        public decimal INVENTARIO_ANU { get; set; }
        public decimal espera_inv { get; set; }
        public decimal inventario { get; set; }
        public decimal Cod_Producto { get; set; }
        public decimal Cod_deposito { get; set; }
        public decimal produccion_formula { get; set; }
        public decimal produccion_orden { get; set; }
        public decimal produccion_orden_esp { get; set; }
        public decimal Presupuesto { get; set; }
        public decimal promventas { get; set; }
        public decimal espera_pre { get; set; }
        public decimal Pedido { get; set; }
        public decimal espera_ped { get; set; }
        public decimal nde { get; set; }
        public decimal ESPERA_NDE { get; set; }
        public decimal NDE_ANULADA { get; set; }
        public decimal detalleinv { get; set; }
        public decimal Factura { get; set; }
        public decimal espera_fac { get; set; }
        public decimal devolucion { get; set; }
        public decimal ESPERA_DEV { get; set; }
        public decimal cambio_precio { get; set; }
        public decimal promocion { get; set; }
        public decimal espera_cam_precio { get; set; }
        public decimal ofertas { get; set; }
        public decimal espera_ofe { get; set; }
        public decimal oferta_anu { get; set; }
        public decimal cod_cliente { get; set; }
        public decimal POS { get; set; }
        public decimal Cierre_par { get; set; }
        public decimal Cierre_tot { get; set; }
        public decimal Deposito { get; set; }
        public decimal Cheque { get; set; }
        public decimal Transmisiones { get; set; }
        public decimal ORGANIZACION { get; set; }
        public decimal cxp_giros { get; set; }
        public decimal cxp_cuotas { get; set; }
        public decimal cxp_notac { get; set; }
        public decimal cxp_notad { get; set; }
        public decimal cxp_pagos { get; set; }
        public decimal cxp_a_p { get; set; }
        public decimal cxc_giros { get; set; }
        public decimal cxc_cuotas { get; set; }
        public decimal cxc_notac { get; set; }
        public decimal cxc_notad { get; set; }
        public decimal cxc_pagos { get; set; }
        public decimal cxc_a_p { get; set; }
        public decimal banco_egreso { get; set; }
        public decimal banco_deposito { get; set; }
        public decimal banco_debito { get; set; }
        public decimal banco_credito { get; set; }
        public decimal banco_anulado { get; set; }
        public decimal banco_operacion { get; set; }
        public decimal banco_conciliacion { get; set; }
        public decimal ejecutables { get; set; }
        public decimal d_moneda { get; set; }
        public int id { get; set; }
        public decimal N_PROD_EXT { get; set; }
        public decimal RELACION { get; set; }
        public decimal N_PLANTILLAS { get; set; }
        public decimal cxp_pagos_prog { get; set; }
        public decimal ProgPago { get; set; }
        public decimal c_consecu_cheque { get; set; }
        public decimal BANCO_TRANSFERENCIA { get; set; }
        public decimal LIQUIDACION_MASIVA { get; set; }
        public decimal NU_COLOCACIONES { get; set; }
        public decimal LIQUIDACION_DIV { get; set; }
        public decimal cambiopremios { get; set; }
    }
}
