//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CXP_PROG
    {
        public string C_Documento { get; set; }
        public string C_Relacion { get; set; }
        public string C_Codigo { get; set; }
        public string C_localidad { get; set; }
        public string C_usuario { get; set; }
        public string c_concepto { get; set; }
        public string c_detalle { get; set; }
        public string c_observacion { get; set; }
        public System.DateTime f_fechae { get; set; }
        public System.DateTime f_fechav { get; set; }
        public double n_impuesto { get; set; }
        public double n_bimpuesto { get; set; }
        public double n_total { get; set; }
        public double n_PagadoImp { get; set; }
        public double n_Pagado { get; set; }
        public double n_retencion { get; set; }
        public double n_subtotal { get; set; }
        public double N_pimpuesto { get; set; }
        public string c_codmoneda { get; set; }
        public double n_factor { get; set; }
        public System.DateTime F_CANCELACION { get; set; }
        public int id { get; set; }
        public int ProgPago { get; set; }
        public int Estado { get; set; }
    }
}
