//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CONFIGURACION_MAIL
    {
        public int id { get; set; }
        public string cu_codigo { get; set; }
        public string cu_descripcion { get; set; }
        public string cu_servidor { get; set; }
        public string cu_puerto { get; set; }
        public bool bu_autenticacion { get; set; }
        public string cu_login { get; set; }
        public string cu_password { get; set; }
        public string cu_correoEmisor { get; set; }
        public string cu_nombreEmisor { get; set; }
        public string cu_correoRespuesta { get; set; }
    }
}
