//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CONFIG_LIBRO
    {
        public string CS_CAMPO { get; set; }
        public string CS_CAMPOTABLA { get; set; }
        public string CS_CAMPORPT { get; set; }
        public int NS_TIPOCAMPO { get; set; }
        public int NS_POSICION { get; set; }
        public bool BS_TOTALIZA { get; set; }
        public int BS_VENTAS { get; set; }
        public int NS_ORDEN { get; set; }
        public int NS_ANCHO { get; set; }
    }
}
