//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CLIENTES_DIRECCIONES
    {
        public decimal ID { get; set; }
        public string CodCliente { get; set; }
        public string TipoDir { get; set; }
        public string Direccion { get; set; }
        public string NombreCorto { get; set; }
        public string UsuarioAdd { get; set; }
        public System.DateTime FechaAdd { get; set; }
        public string Host_Name { get; set; }
    }
}
