//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CAMBIOS_PREMIOS
    {
        public string cs_codigocliente { get; set; }
        public System.DateTime ds_fechacambio { get; set; }
        public string cs_documento { get; set; }
        public string cs_usuario { get; set; }
        public string cs_tipo { get; set; }
        public string CS_SUCURSAL { get; set; }
    }
}
