//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DENOMINACIONES
    {
        public string c_codmoneda { get; set; }
        public string c_coddenomina { get; set; }
        public string c_denominacion { get; set; }
        public double n_valor { get; set; }
        public bool c_real { get; set; }
        public bool c_pos { get; set; }
        public double n_monto_compra { get; set; }
        public double n_monto_vuelto { get; set; }
        public bool b_permite_vuelto { get; set; }
        public int nu_requiere_endoso { get; set; }
        public int nu_imprime_forma { get; set; }
        public int nu_requiere_conformacion { get; set; }
        public int nu_requiere_serial { get; set; }
        public int nu_verificacionElectronica { get; set; }
        public bool bs_verificacionoperaciones_especiales { get; set; }
        public bool bs_credito { get; set; }
        public bool bAutoDeclaracion { get; set; }
    }
}
