//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DENOMINA_RES_INGRESOS
    {
        public string cs_denominacion { get; set; }
        public string cs_tipo { get; set; }
        public string cs_descri { get; set; }
        public decimal id { get; set; }
    }
}
