//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DEPOPROD
    {
        public string c_coddeposito { get; set; }
        public string c_codarticulo { get; set; }
        public string c_descripcion { get; set; }
        public double n_cantidad { get; set; }
        public double n_cant_comprometida { get; set; }
        public double n_cant_ordenada { get; set; }
        public decimal ID { get; set; }
    }
}
