//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DATOS_FISCALES
    {
        public string C_NUMEROZ { get; set; }
        public string C_CAJA { get; set; }
        public decimal NU_TURNO { get; set; }
        public string CS_CODCAJERO { get; set; }
        public string CS_CAJERO { get; set; }
        public System.DateTime D_FECHA { get; set; }
        public string C_DOCINICIALVEN { get; set; }
        public string C_DOCFINALVEN { get; set; }
        public double F_MONTOBASEVENA { get; set; }
        public double F_MONTOBASEVENB { get; set; }
        public double F_MONTOBASEVENC { get; set; }
        public double F_IMPUESTOVENA { get; set; }
        public double F_IMPUESTOVENB { get; set; }
        public double F_IMPUESTOVENC { get; set; }
        public double F_EXCENTOVEN { get; set; }
        public double F_MONTOTOTALVEN { get; set; }
        public decimal CODCONCEPTO { get; set; }
        public string C_CONCEPTO { get; set; }
        public double F_IMPUESTOTOTALVEN { get; set; }
        public string CS_NUMERO_TRANSFERENCIA { get; set; }
        public string cs_comprobantecontable { get; set; }
        public string C_LOCALIDAD { get; set; }
    }
}
