//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DEPOSITO
    {
        public string c_coddeposito { get; set; }
        public string c_descripcion { get; set; }
        public string c_codlocalidad { get; set; }
        public string c_responsable { get; set; }
        public string c_observacion { get; set; }
        public System.DateTime update_date { get; set; }
        public System.DateTime add_date { get; set; }
        public string cu_mascara { get; set; }
        public decimal id { get; set; }
    }
}
