//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DISPOSITIVOS
    {
        public string C_CODIGO { get; set; }
        public int N_PUERTO { get; set; }
        public double N_BAUDIOS { get; set; }
        public string C_PARIDAD { get; set; }
        public int N_DATO { get; set; }
        public int N_PARADA { get; set; }
        public string C_PARALELO { get; set; }
        public string C_TecnSele { get; set; }
        public string C_OPOS { get; set; }
    }
}
