//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ERRORCORRIDAS_AGENTE_ADM
    {
        public string equipo { get; set; }
        public string corrida { get; set; }
        public string error { get; set; }
        public decimal nerror { get; set; }
        public string sucursal { get; set; }
        public string tabla { get; set; }
        public string codigo { get; set; }
        public string concepto { get; set; }
        public System.DateTime fecha { get; set; }
        public int tipo { get; set; }
        public string rutina { get; set; }
        public System.DateTime fechahora { get; set; }
        public decimal id { get; set; }
    }
}
