//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ENTREGAS
    {
        public string Documento { get; set; }
        public string Descripcion { get; set; }
        public string RIF { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Telefono { get; set; }
        public byte[] Imagen { get; set; }
        public string PedidoRelacion { get; set; }
        public string Factura { get; set; }
    }
}
