//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ELAB_INVENTARIO
    {
        public bool B_COMENZADO { get; set; }
        public System.DateTime F_INiCIO { get; set; }
        public bool B_FINALIZADO { get; set; }
        public Nullable<System.DateTime> F_FINAL { get; set; }
        public string c_coddeposito { get; set; }
        public string C_MOTIVO { get; set; }
        public decimal no_elab { get; set; }
        public string c_codmoneda { get; set; }
        public double n_factor { get; set; }
        public string CU_CODDEPARTAMENTO { get; set; }
        public string CU_CODGRUPO { get; set; }
        public string CU_CODSUBGRUPO { get; set; }
        public string cu_CODPROVEEDOR { get; set; }
    }
}
