//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_FORMATO_BANCOS
    {
        public string cu_codigoFormato { get; set; }
        public string cu_nombreFormato { get; set; }
        public string cu_ubicacion { get; set; }
        public string codigoCuentaCorriente { get; set; }
        public string codigoCuentaAhorro { get; set; }
        public string codigoAbonoCuenta { get; set; }
        public string codigoTransferenciaSwift { get; set; }
        public string codigoChequeGerencia { get; set; }
    }
}
