//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_HISTORICO_COSTO_PRECIO
    {
        public string c_Historico { get; set; }
        public System.DateTime d_FechaCambio { get; set; }
        public string c_ProcesoOrigen { get; set; }
        public string c_Documento { get; set; }
        public string c_Usuario { get; set; }
        public string c_CodArticulo { get; set; }
        public double Precio1_Ant { get; set; }
        public double Precio1_Nuevo { get; set; }
        public double Precio2_Ant { get; set; }
        public double Precio2_Nuevo { get; set; }
        public double Precio3_Ant { get; set; }
        public double Precio3_Nuevo { get; set; }
        public double CostoAct_Ant { get; set; }
        public double CostoAct_Nuevo { get; set; }
        public double CostoRep_Ant { get; set; }
        public double CostoRep_Nuevo { get; set; }
        public int ID { get; set; }
        public double CostoAnt_Ant { get; set; }
        public double CostoAnt_Nuevo { get; set; }
        public double CostoPro_Ant { get; set; }
        public double CostoPro_Nuevo { get; set; }
    }
}
