//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_INVENTARIOxDOCUMENTO
    {
        public string CS_DOCUMENTO { get; set; }
        public string CS_CONCEPTO { get; set; }
        public string CS_DOCUMENTO_ORIGEN { get; set; }
        public string CS_CONCEPTO_ORIGEN { get; set; }
        public string CS_ESTATUS { get; set; }
    }
}
