//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_INV_FISICO
    {
        public string c_DOCUMENTO { get; set; }
        public System.DateTime d_FECHA { get; set; }
        public string c_STATUS { get; set; }
        public string c_CODLOCALIDAD { get; set; }
        public string c_codMONEDA { get; set; }
        public double n_FACTORCAMBIO { get; set; }
        public string c_OBSERVACION { get; set; }
        public string c_CODCOMPRADOR { get; set; }
        public string c_DEP_ORIG { get; set; }
        public string c_MOTIVO { get; set; }
        public decimal NO_ELAB { get; set; }
        public string CU_CODDEPARTAMENTO { get; set; }
        public string CU_CODGRUPO { get; set; }
        public string CU_CODSUBGRUPO { get; set; }
        public string CU_CODPROVEEDOR { get; set; }
        public decimal ID { get; set; }
    }
}
