//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_INVENTARIO_REPORTE_TMP
    {
        public string c_documento { get; set; }
        public string c_concepto { get; set; }
        public string c_relacion { get; set; }
        public string c_codproveedor { get; set; }
        public System.DateTime d_fecha { get; set; }
        public string c_descripcion { get; set; }
        public string cs_usuario { get; set; }
    }
}
