//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_INVENTARIO
    {
        public string c_CONCEPTO { get; set; }
        public string c_DOCUMENTO { get; set; }
        public System.DateTime d_FECHA { get; set; }
        public string c_DESCRIPCION { get; set; }
        public string c_STATUS { get; set; }
        public string c_CODPROVEEDOR { get; set; }
        public string c_CODLOCALIDAD { get; set; }
        public string c_codmoneda { get; set; }
        public double n_FACTORCAMBIO { get; set; }
        public double n_DESCUENTO { get; set; }
        public string c_OBSERVACION { get; set; }
        public string c_RELACION { get; set; }
        public string c_CODCOMPRADOR { get; set; }
        public string c_DEP_ORIG { get; set; }
        public string c_DEP_DEST { get; set; }
        public string c_MOTIVO { get; set; }
        public string c_codtransporte { get; set; }
        public string c_ejecutor { get; set; }
        public string c_factura { get; set; }
        public string c_transportista { get; set; }
        public double n_cantidad_compra { get; set; }
        public decimal id { get; set; }
        public decimal CODCONCEPTO { get; set; }
        public string cs_comprobanteContable { get; set; }
        public System.DateTime ds_horainicio { get; set; }
        public System.DateTime ds_horafinal { get; set; }
        public string CS_CODLOCALIDAD { get; set; }
        public string CS_NUMERO_TRANSFERENCIA { get; set; }
        public string CS_CODUNIDAD { get; set; }
        public string CS_NUMTRANSF_DESTINO { get; set; }
        public System.DateTime dFechaRegistro { get; set; }
    }
}
