//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_IMPRESORAS_ETIQUETAS
    {
        public string cCodigo { get; set; }
        public string cDescripcion { get; set; }
        public bool bIngreso { get; set; }
        public System.DateTime fFechaIngreso { get; set; }
        public string cUsuario { get; set; }
    }
}
