//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_LIBROS_CONFIGURADOS
    {
        public string cs_documento { get; set; }
        public string cs_titulo { get; set; }
        public string cs_piepagina { get; set; }
        public bool bs_mostrarresumen { get; set; }
        public decimal ns_anchototal { get; set; }
        public string cs_tipopagina { get; set; }
        public bool bs_activo { get; set; }
        public bool bs_ventas { get; set; }
    }
}
