//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_MONEDAS
    {
        public string c_codmoneda { get; set; }
        public string c_descripcion { get; set; }
        public double n_factor { get; set; }
        public bool b_preferencia { get; set; }
        public string c_observacio { get; set; }
        public bool b_activa { get; set; }
        public string c_simbolo { get; set; }
        public int n_decimales { get; set; }
        public bool bUsoEnPOS { get; set; }
    }
}
