//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_MODIFICACIONESRECMOVIL
    {
        public string usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string numeroODC { get; set; }
        public string codigoProveedor { get; set; }
        public decimal id { get; set; }
        public string documento { get; set; }
    }
}
