//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ORDEN_PRODUCCION
    {
        public string c_Documento { get; set; }
        public System.DateTime d_Fecha { get; set; }
        public string c_Status { get; set; }
        public string c_CodLocalidad { get; set; }
        public string c_CodMoneda { get; set; }
        public double n_FactorCambio { get; set; }
        public double n_CostoDir { get; set; }
        public string c_Observacion { get; set; }
        public bool b_BackOrder { get; set; }
        public string c_Relacion { get; set; }
        public string c_Formula { get; set; }
        public string c_Descripcion { get; set; }
        public string c_Usuario { get; set; }
        public System.DateTime d_Fecha_Produccion { get; set; }
        public double n_Subtotal { get; set; }
        public double n_MontoMerma { get; set; }
        public double n_Descuento { get; set; }
        public double n_Impuesto { get; set; }
        public double n_Total { get; set; }
        public Nullable<System.DateTime> d_FechaVencimiento { get; set; }
        public string cs_CodLocalidad { get; set; }
        public decimal ID { get; set; }
        public string c_LineaProduccion { get; set; }
        public string c_Turno { get; set; }
        public string c_Referencia { get; set; }
        public string Host_Name { get; set; }
        public string TxtPlus1 { get; set; }
        public string TxtPlus2 { get; set; }
    }
}
