//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_OFERTAS_PERMANENTES
    {
        public string cs_codigooferta { get; set; }
        public string cs_descripcion { get; set; }
        public string cs_departamento { get; set; }
        public string cs_grupo { get; set; }
        public string cs_subgrupo { get; set; }
        public bool bs_regulados { get; set; }
        public bool bs_activo { get; set; }
        public double ns_porcentaje { get; set; }
        public bool bs_lunes { get; set; }
        public bool bs_martes { get; set; }
        public bool bs_miercoles { get; set; }
        public bool bs_jueves { get; set; }
        public bool bs_viernes { get; set; }
        public bool bs_sabado { get; set; }
        public bool bs_domingo { get; set; }
        public bool bs_Afiliados { get; set; }
        public double ns_margenUtilidad { get; set; }
    }
}
