//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ODC_AUTOMATICAS
    {
        public string cu_proveedor { get; set; }
        public string cu_diasCorrer { get; set; }
        public int nu_orden { get; set; }
        public string cu_forma { get; set; }
        public string cu_deposito { get; set; }
        public int nu_dias { get; set; }
        public int nu_tipoCosto { get; set; }
        public int nu_tipoPrecio { get; set; }
        public string cu_localidad { get; set; }
    }
}
