//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_OPBANCOS
    {
        public double n_montomax { get; set; }
        public double n_diasMb { get; set; }
        public double n_diasPb { get; set; }
        public double n_diasOPB { get; set; }
        public double n_numcomprobante { get; set; }
        public double n_numdebito { get; set; }
        public double n_numcredito { get; set; }
        public double n_numdeposito { get; set; }
        public double n_MontoDebito { get; set; }
        public bool B_ConsiliarADM { get; set; }
        public bool B_ConsiliaContabilidad { get; set; }
    }
}
