//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_OFERTAS
    {
        public string c_documento { get; set; }
        public System.DateTime f_desde { get; set; }
        public System.DateTime f_hasta { get; set; }
        public System.DateTime h_desde { get; set; }
        public System.DateTime h_hasta { get; set; }
        public string c_horad { get; set; }
        public string c_horah { get; set; }
        public string c_status { get; set; }
        public System.DateTime fs_fecha_hora { get; set; }
        public string c_observacion { get; set; }
        public string c_usuario { get; set; }
        public string c_codlocalidad { get; set; }
    }
}
