//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PROVEEDORESxCLIENTE
    {
        public string cu_codcliente { get; set; }
        public string cu_codproveedor { get; set; }
        public string cs_codusuario { get; set; }
        public System.DateTime ds_fechaingreso { get; set; }
        public System.DateTime ds_fechamodificacion { get; set; }
        public decimal id { get; set; }
    }
}
