//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PROVEEDORES
    {
        public string c_codproveed { get; set; }
        public string c_descripcio { get; set; }
        public string c_grupo { get; set; }
        public string c_rif { get; set; }
        public string c_representa { get; set; }
        public string c_cargo { get; set; }
        public string c_direccion { get; set; }
        public string c_ciudad { get; set; }
        public string c_estado { get; set; }
        public string c_pais { get; set; }
        public string c_email { get; set; }
        public string c_telefono { get; set; }
        public string c_celular { get; set; }
        public string c_fax { get; set; }
        public string c_web { get; set; }
        public double n_limite { get; set; }
        public int n_dias { get; set; }
        public double n_porcentaje { get; set; }
        public string c_observacio { get; set; }
        public string c_nit { get; set; }
        public int n_activo { get; set; }
        public System.DateTime update_date { get; set; }
        public System.DateTime add_date { get; set; }
        public string c_razon { get; set; }
        public string c_codreferencial { get; set; }
        public string c_contacto_adm { get; set; }
        public string c_contacto_ven { get; set; }
        public string c_contacto_reg { get; set; }
        public string c_contacto_vdd { get; set; }
        public string c_email_adm { get; set; }
        public string c_email_ven { get; set; }
        public string c_email_reg { get; set; }
        public string c_email_vdd { get; set; }
        public string c_email_fiscal { get; set; }
        public string c_email_depo { get; set; }
        public string c_telefono_rep { get; set; }
        public string c_telefono_adm { get; set; }
        public string c_telefono_ven { get; set; }
        public string c_telefono_reg { get; set; }
        public string c_telefono_vdd { get; set; }
        public string c_celular_adm { get; set; }
        public string c_celular_ven { get; set; }
        public string c_celular_reg { get; set; }
        public string c_celular_vdd { get; set; }
        public string c_direccion_dep { get; set; }
        public string c_ciudad_dep { get; set; }
        public string c_estado_dep { get; set; }
        public string c_pais_dep { get; set; }
        public string c_telefono_dep { get; set; }
        public string c_fax_dep { get; set; }
        public string c_email_dep { get; set; }
        public string c_cod_banco { get; set; }
        public string c_cuenta_banco { get; set; }
        public string c_cuentahabiente { get; set; }
        public int n_dia2 { get; set; }
        public double n_porcentaje2 { get; set; }
        public int n_dia3 { get; set; }
        public double n_porcentaje3 { get; set; }
        public string c_codlicores { get; set; }
        public int n_diasdespacho { get; set; }
        public int B_PREFERENCIAL { get; set; }
        public double N_RETENCION { get; set; }
        public string CS_COMPRADOR { get; set; }
        public bool bu_cualquier_cuenta { get; set; }
        public string cs_tipo { get; set; }
        public decimal id { get; set; }
        public string c_rim { get; set; }
        public int n_diasreposicion { get; set; }
        public int n_diasanalisis { get; set; }
        public int n_descaveria { get; set; }
        public bool b_enviarOdcL { get; set; }
        public bool b_enviarOdcA { get; set; }
        public bool b_enviarOdcV { get; set; }
        public bool b_enviarOdcR { get; set; }
        public bool b_enviarOdcVen { get; set; }
        public double n_porcentaje_seniat { get; set; }
        public string c_UsuarioAdd { get; set; }
        public string c_UsuarioUpd { get; set; }
    }
}
