//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PAGOS_ELECTRONICOS
    {
        public int ID { get; set; }
        public string codigo { get; set; }
        public string codigoBanco { get; set; }
        public string banco { get; set; }
        public string cuenta { get; set; }
        public decimal montoPresupuestado { get; set; }
        public System.DateTime fechaLiberacion { get; set; }
        public decimal saldoEnLibros { get; set; }
        public decimal diferido { get; set; }
        public decimal debitosEstimados { get; set; }
        public decimal totalPago { get; set; }
        public string estado { get; set; }
        public System.DateTime fechaEmision { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<System.DateTime> fechaArchivo { get; set; }
    }
}
