//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PLANTILLAS
    {
        public decimal id { get; set; }
        public string c_cod_plantilla { get; set; }
        public string descripcion { get; set; }
        public string relacion { get; set; }
        public string tiporel { get; set; }
        public string clave { get; set; }
        public string texto { get; set; }
        public string imagen { get; set; }
        public string tag { get; set; }
        public string campo { get; set; }
        public int prioridad { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public decimal tamanocolgrid { get; set; }
        public string tipoproducto { get; set; }
        public string campoclave { get; set; }
        public bool esgrupo { get; set; }
        public bool AutoIntervalo { get; set; }
    }
}
