//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PRODUCTOS_ARCHIVO_EXISTENTE
    {
        public string cs_codigoprod { get; set; }
        public string cs_codigoprov { get; set; }
        public string cs_descriprod { get; set; }
        public string cs_motivo { get; set; }
        public System.DateTime ds_fecha { get; set; }
        public decimal id { get; set; }
    }
}
