//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PROVEEDORES_DATOSBANCARIOS
    {
        public string codigoProveedor { get; set; }
        public string Banco { get; set; }
        public string numeroCuenta { get; set; }
        public string cuentahabiente { get; set; }
        public string tipoCuenta { get; set; }
        public string tipoPago { get; set; }
        public string codigoSwift { get; set; }
        public string codigoAba { get; set; }
        public string idBeneficiario { get; set; }
    }
}
