//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PEDIDOS_RUTA
    {
        public string cs_Corrida { get; set; }
        public System.DateTime d_Fecha { get; set; }
        public System.DateTime d_FechaCorrida { get; set; }
        public string c_Usuario { get; set; }
        public string c_Zona { get; set; }
        public string c_Ruta { get; set; }
        public string c_Transporte { get; set; }
        public bool b_Facturada { get; set; }
        public bool Picking { get; set; }
        public bool Packing { get; set; }
        public decimal nTipoSeparacionDetalle { get; set; }
    }
}
