//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PROCESOS
    {
        public decimal IDProceso { get; set; }
        public string Proceso { get; set; }
        public string Tabla { get; set; }
        public string Concepto { get; set; }
        public string Documento { get; set; }
        public int AceptaClasificacion { get; set; }
        public decimal IDProcesoEmisor { get; set; }
    }
}
