//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PRODUCCION
    {
        public string C_FORMULA { get; set; }
        public string C_DESCRIPCION { get; set; }
        public string C_STATUS { get; set; }
        public string C_CODUSUARIO { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ADD_DATE { get; set; }
        public string c_codlocalidad { get; set; }
        public double N_COSTODIR { get; set; }
        public string C_CODMONEDA { get; set; }
        public string c_Instrucciones { get; set; }
        public double n_TiempoPreparacion { get; set; }
    }
}
