//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PEDIDOS_RUTA_AUTORIZACIONES
    {
        public string cs_Corrida { get; set; }
        public string c_Documento_Ped { get; set; }
        public string c_Documento_Ven { get; set; }
        public string c_Cliente { get; set; }
        public string c_DescriCliente { get; set; }
        public string c_Usuario_Auto { get; set; }
        public decimal ID { get; set; }
    }
}
