//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PRODUCCION_CAPACIDAD_MAXIMA
    {
        public string c_CodArticulo { get; set; }
        public string c_CodLocalidad { get; set; }
        public string c_LineaProduccion { get; set; }
        public double nCapacidadEmpaques { get; set; }
        public double nCapacidadUnidades { get; set; }
        public string cTipoFrecuencia { get; set; }
        public double nCantidadFrecuencia { get; set; }
    }
}
