//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PROGRAMADOR_PAGOS
    {
        public string CS_CODIGO { get; set; }
        public System.DateTime DS_FECHA { get; set; }
        public System.DateTime DS_FECHAPAGO { get; set; }
        public string CS_CODPROVEEDOR { get; set; }
        public string CS_PROVEEDOR { get; set; }
        public string CS_USUARIO { get; set; }
        public string CS_LOCALIDAD { get; set; }
        public string CS_LOCALIDADORIGEN { get; set; }
        public string CS_ESTATUS { get; set; }
        public string CS_MONEDA { get; set; }
        public double NS_TOTAL_CANCELAR { get; set; }
        public double NS_TOTAL_CANCELARCxP { get; set; }
        public double NS_TOTAL_CANCELARCxC { get; set; }
        public string cs_observacion { get; set; }
        public System.DateTime ds_fecha_proceso { get; set; }
        public string cs_usuario_proceso { get; set; }
        public string c_EstatusAprobacion { get; set; }
        public string c_ProgramacionMasiva { get; set; }
    }
}
