//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PROGRAMACIONPAGO_MASIVA
    {
        public string c_CodigoProg { get; set; }
        public System.DateTime d_FechaCreacion { get; set; }
        public string c_Usuario { get; set; }
        public string c_Status { get; set; }
        public string c_LocalidadOrigen { get; set; }
        public string c_Moneda { get; set; }
        public double n_TotalCxP { get; set; }
        public double n_TotalCxC { get; set; }
        public double n_TotalGeneral { get; set; }
        public string c_Observacion { get; set; }
    }
}
