//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_REGLASDENEGOCIO
    {
        public string IDModulo { get; set; }
        public string IDProceso { get; set; }
        public string Campo { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public string ValorDefault { get; set; }
        public string ValoresPermitidos { get; set; }
        public string Valor { get; set; }
        public bool Oculto { get; set; }
    }
}
