//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_RECEPCIONESMOVIL
    {
        public string codigoProveedor { get; set; }
        public string codigoODC { get; set; }
        public string codigoProducto { get; set; }
        public double cantidadUnidades { get; set; }
        public double cantidadEmpaques { get; set; }
        public double facturaUnidades { get; set; }
        public double facturaEmpaques { get; set; }
        public string transportista { get; set; }
        public string codigoLocalidad { get; set; }
        public string codigoDeposito { get; set; }
        public string documento { get; set; }
        public string numeroRecepcion_PDA { get; set; }
        public double UnidadesxEmpaque { get; set; }
        public string numeroFactura { get; set; }
        public string Observacion { get; set; }
    }
}
