//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_REQUISICIONES
    {
        public string CS_DOCUMENTO { get; set; }
        public System.DateTime DS_FECHA { get; set; }
        public string CS_ESTADO { get; set; }
        public string CS_CODLOCALIDAD { get; set; }
        public string CS_OBSERVACION { get; set; }
        public string CS_RELACION { get; set; }
        public string CS_CODOPERADOR { get; set; }
        public System.DateTime DS_FECHA_TOPE { get; set; }
        public string CS_DEPOSITO_SOLICITUD { get; set; }
        public string CS_DEPOSITO_DESPACHAR { get; set; }
        public int NU_ESTADO_INTERNO { get; set; }
        public int NU_PRIORIDAD { get; set; }
        public string CS_CODMONEDA { get; set; }
        public double NS_FACTOR_CAMBIO { get; set; }
        public string cs_Numero_Transferencia { get; set; }
        public string cs_NumTransf_Destino { get; set; }
    }
}
