//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_RETENCIONES
    {
        public string CS_RETENCION { get; set; }
        public string CS_DESCRIPCION { get; set; }
        public decimal NU_CONCEPTO { get; set; }
        public int NU_ITEM_APLICAR { get; set; }
        public double NU_PORCENTAJE_APLICAR { get; set; }
        public int NU_EVENTO { get; set; }
        public bool NU_APLICAR_PROVEEDORES { get; set; }
        public bool NU_ACEPTA_PARCIALES { get; set; }
        public int NU_NIVEL { get; set; }
        public string cs_correlativo { get; set; }
        public double NS_MONTOMIN { get; set; }
        public double NS_PORCBASE { get; set; }
        public double NS_SUSTRAENDO { get; set; }
    }
}
