//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_REPORTES
    {
        public int CodPlantilla { get; set; }
        public string Descripcion { get; set; }
        public string TipoNomina { get; set; }
        public string Ubicacion { get; set; }
        public string Archivo { get; set; }
        public bool Reescribir { get; set; }
        public bool Fecha { get; set; }
        public string Servidor { get; set; }
        public string BaseDatos { get; set; }
    }
}
