//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_SUCURSALES
    {
        public string C_codigo { get; set; }
        public string c_descripcion { get; set; }
        public string c_direccion { get; set; }
        public string c_gerente { get; set; }
        public string c_subgerebte { get; set; }
        public string c_telefono { get; set; }
        public int c_estado { get; set; }
        public string c_servidor { get; set; }
        public bool B_TRASMITIR { get; set; }
        public bool B_ACTVAD10 { get; set; }
        public string c_ciudad { get; set; }
        public string c_nombre_cheque { get; set; }
        public string cu_DireccionUltimaVersion { get; set; }
        public int nu_ActualizarUltimaVersion { get; set; }
        public int nu_MensajeUltimaVersion { get; set; }
        public string c_Rif { get; set; }
        public string c_Grupo { get; set; }
    }
}
