//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_SOLICITUD
    {
        public string c_DOCUMENTO { get; set; }
        public System.DateTime d_FECHA { get; set; }
        public string c_status { get; set; }
        public string c_CODPROVEEDOR { get; set; }
        public string c_CODLOCALIDAD { get; set; }
        public string c_codmoneda { get; set; }
        public double n_FACTORCAMBIO { get; set; }
        public string c_OBSERVACION { get; set; }
        public double N_SUBTOTAL { get; set; }
        public double N_IMPUESTO { get; set; }
        public double N_TOTAL { get; set; }
        public string C_USUARIO { get; set; }
        public decimal id { get; set; }
        public string cs_codlocalidad { get; set; }
    }
}
