//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TABLAS_CONSOLIDAR_SUCURSALES
    {
        public string cu_codsucursal { get; set; }
        public decimal cu_codtablassyncronizar { get; set; }
        public string cu_descripcion { get; set; }
        public string cu_mensajeEliminar { get; set; }
        public string cu_mensaje { get; set; }
        public string cu_tabla_maestra { get; set; }
        public string cu_campob_maestra { get; set; }
        public string cu_tabla_TR { get; set; }
        public string cu_campob_TR { get; set; }
        public string cu_tabla_tr_pend { get; set; }
        public string cu_campob_tr_pend { get; set; }
        public int nu_proceso { get; set; }
        public string cu_camposExepcion { get; set; }
        public string cu_camposExepcionTr { get; set; }
        public string cu_criteriorrestriction { get; set; }
        public string cu_criteriorestriccionMa { get; set; }
        public string cu_criteriorestriccionTr { get; set; }
        public string cu_campo_correlativo { get; set; }
        public decimal cu_correlativo { get; set; }
        public string cu_concepto { get; set; }
        public string cu_comentario_concepto { get; set; }
        public string cu_formato { get; set; }
        public bool bu_activar { get; set; }
    }
}
