//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TRAZA_FICHAS
    {
        public decimal CS_ID { get; set; }
        public string CS_FICHA { get; set; }
        public string CS_CODIGO_USUARIO { get; set; }
        public string CS_TIPO_OPERACION { get; set; }
        public System.DateTime CS_FECHA_OPERACION { get; set; }
        public string CS_CODIGO { get; set; }
        public int CS_TIPO_OBJETO { get; set; }
    }
}
