//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TRIBUTOS
    {
        public string c_codigo { get; set; }
        public string c_descripcio { get; set; }
        public string c_termino { get; set; }
        public double n_alicuota { get; set; }
        public string c_clasificacion { get; set; }
        public bool c_ventas { get; set; }
        public bool c_compras { get; set; }
        public string c_renta { get; set; }
    }
}
