//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TEMP_REP_HISTORICO
    {
        public string c_codarticulo { get; set; }
        public double Saldo { get; set; }
        public double valorHistorico { get; set; }
        public string c_descripcion { get; set; }
        public string c_deposito { get; set; }
        public string c_departamento { get; set; }
        public string c_grupo { get; set; }
        public string c_subgrupo { get; set; }
    }
}
