//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TRANSPORTE
    {
        public string c_codtransporte { get; set; }
        public string c_descripcion { get; set; }
        public string C_PLACA { get; set; }
        public string C_COLOR { get; set; }
        public string C_MARCA { get; set; }
        public string C_MODELO { get; set; }
        public string C_RESPONSABLE { get; set; }
        public string C_CODLOCALIDAD { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ADD_DATE { get; set; }
        public double n_Peso { get; set; }
        public double n_Volumen { get; set; }
    }
}
