//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_UBICACIONxCATEGORIA
    {
        public string cu_Deposito { get; set; }
        public string cu_Departamento { get; set; }
        public string cu_Grupo { get; set; }
        public string cu_SubGrupo { get; set; }
        public string cu_Mascara { get; set; }
        public decimal ID { get; set; }
    }
}
