//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_USUARIOS
    {
        public string codusuario { get; set; }
        public string password { get; set; }
        public string login_name { get; set; }
        public string descripcion { get; set; }
        public string clave { get; set; }
        public string localidad { get; set; }
        public decimal Nivel { get; set; }
        public decimal Vendedor { get; set; }
        public System.DateTime add_date { get; set; }
        public System.DateTime update_date { get; set; }
        public bool tipo_usuario { get; set; }
        public bool MOD_PRECIO_VENTA { get; set; }
        public bool MOD_COSTO_COMPRA { get; set; }
        public int BU_CAMBIA_CLAVE { get; set; }
        public decimal ID { get; set; }
        public bool BS_ACTIVO { get; set; }
    }
}
