//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGLAS_COMERCIALES
    {
        public int Estimacion_PV { get; set; }
        public bool Auto_codigo { get; set; }
        public double caracter_codigo { get; set; }
        public bool Auto_banco { get; set; }
        public double caracter_banco { get; set; }
        public bool Auto_cliente { get; set; }
        public double caracter_cliente { get; set; }
        public bool Auto_deposito { get; set; }
        public double caracter_deposito { get; set; }
        public bool Auto_moneda { get; set; }
        public double caracter_moneda { get; set; }
        public bool Auto_localidad { get; set; }
        public double caracter_localidad { get; set; }
        public bool Auto_proveedor { get; set; }
        public double caracter_proveedor { get; set; }
        public bool Auto_usuario { get; set; }
        public double caracter_usuario { get; set; }
        public int TIPO_REDONDEO { get; set; }
        public bool redondear_mitad { get; set; }
        public bool considerar_imp { get; set; }
        public bool REDONDEAR_PRECIOS { get; set; }
        public int NIVEL_MOD_PRECIOS { get; set; }
        public double IMPUESTO { get; set; }
        public bool VARIAR9 { get; set; }
        public int NIVEL_MOD_COSTOS { get; set; }
        public bool MANEJA_POS { get; set; }
        public int ESTIMACION_INV { get; set; }
        public int NIVEL_CIERRE_FORZADO { get; set; }
        public bool mas_productos { get; set; }
        public string ARCHIVO_BALANZA { get; set; }
        public bool FACTURA_ENCABEZADO { get; set; }
        public Nullable<int> NO_PUNTOS { get; set; }
        public bool MUESTRAIMPFAC { get; set; }
        public bool AUTO_VENDEDOR { get; set; }
        public bool BLN_RTF_REPLACE_ONE { get; set; }
        public bool BU_VENDEDOR { get; set; }
        public string CARACTER_VENDEDOR { get; set; }
        public string CU_CLIENTE_CONTADO { get; set; }
        public string IMPRESORA_ETIQUETA { get; set; }
        public int NIVEL_Autorizacion_credito { get; set; }
        public bool bAceptarRecSinOrden { get; set; }
        public bool bnivelcambioprecio { get; set; }
    }
}
