//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_FACTOR_PRECIO
    {
        public decimal ID { get; set; }
        public string cCodProducto { get; set; }
        public string cCodMoneda { get; set; }
        public double nFactor { get; set; }
        public double nConversion { get; set; }
        public int nTipoValor { get; set; }
    }
}
