//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_PROGRAMACIONPAGO_MASIVA
    {
        public string c_CodProg { get; set; }
        public string c_Factura { get; set; }
        public string c_TipoDocOrigen { get; set; }
        public double n_Desc1 { get; set; }
        public double n_Desc2 { get; set; }
        public double n_Desc3 { get; set; }
    }
}
