//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_AUX_GASTO
    {
        public string c_detalle { get; set; }
        public string c_factura { get; set; }
        public string c_codprovee { get; set; }
        public string c_grupo { get; set; }
        public string c_descripcion { get; set; }
        public double n_monto { get; set; }
        public string c_item { get; set; }
        public string C_CODIGO { get; set; }
    }
}
