//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_BANCO_REG_DEP
    {
        public string C_codbanco { get; set; }
        public string C_ncuenta { get; set; }
        public string C_documentoint { get; set; }
        public string C_ChequeNo { get; set; }
        public string C_codbancoche { get; set; }
        public string c_plaza { get; set; }
        public double n_monto { get; set; }
        public System.DateTime f_fechal { get; set; }
        public bool b_anulado { get; set; }
        public bool b_aplicado { get; set; }
        public decimal id { get; set; }
    }
}
