//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_BANCO_PRECONCILIACION
    {
        public string c_documentoint { get; set; }
        public string c_concepto { get; set; }
        public string c_ncuenta { get; set; }
        public string c_codbanco { get; set; }
        public decimal ID { get; set; }
    }
}
