//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_BANCO_BENEFICIARIO
    {
        public string c_documentoint { get; set; }
        public string C_concepto { get; set; }
        public string C_beneficiario { get; set; }
        public decimal id { get; set; }
        public string C_CODBANCODESTINO { get; set; }
        public string C_CUENTA { get; set; }
        public decimal CODCONCEPTO { get; set; }
        public string CU_DOCUMENTO { get; set; }
        public string CU_TIPO_DOCUMENTO { get; set; }
        public decimal N_MONTO { get; set; }
        public string CU_DOCUMNETO { get; set; }
        public string CU_TPO_DOCUMENTO { get; set; }
        public string C_CODBEN { get; set; }
        public string C_CODBENEFICIARIO { get; set; }
    }
}
