//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CONS_PRECIOS
    {
        public int N_LINEA { get; set; }
        public string C_DOCUMENTO { get; set; }
        public string C_CODARTICULO { get; set; }
        public string C_DESCRIPCION { get; set; }
        public string c_modelo { get; set; }
        public double N_COSTOACT { get; set; }
        public double N_DESC1 { get; set; }
        public double N_DESC2 { get; set; }
        public double N_DESC3 { get; set; }
        public double N_COSTOFIN { get; set; }
        public string C_DEPARTAMENTO { get; set; }
        public string C_GRUPO { get; set; }
        public string C_SUBGRUPO { get; set; }
        public string N_PROD_EXT { get; set; }
        public string C_CAMXREP { get; set; }
        public double N_PRECIO_REP1 { get; set; }
        public double N_PRECIO_REP2 { get; set; }
        public double N_PRECIO_REP3 { get; set; }
        public double N_COSTOREP { get; set; }
        public double n_FactorMonedaProd { get; set; }
    }
}
