//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_COMPRAS
    {
        public string c_DOCUMENTO { get; set; }
        public decimal ID { get; set; }
        public string C_CONCEPTO { get; set; }
        public string c_CODARTICULO { get; set; }
        public double n_CANTIDAD { get; set; }
        public double n_COSTO { get; set; }
        public double n_subtotal { get; set; }
        public double n_impuesto { get; set; }
        public double n_total { get; set; }
        public double n_porcentajeimp { get; set; }
        public double n_porcentajeimp1 { get; set; }
        public double n_porcentajeimp2 { get; set; }
        public string c_codprincipal { get; set; }
        public double n_COSTOORIGINAL { get; set; }
        public string C_TIPODOC { get; set; }
        public string C_DOC { get; set; }
        public string C_DEPOSITO { get; set; }
        public double N_CPRECIO1 { get; set; }
        public double N_CPRECIO2 { get; set; }
        public double N_CPRECIO3 { get; set; }
        public double N_CPRECIOR { get; set; }
        public bool B_INGRESAR { get; set; }
        public string N_Prod_ext { get; set; }
        public decimal codconcepto { get; set; }
        public string c_id { get; set; }
        public string c_descripcion { get; set; }
        public double n_descuentoespecifico { get; set; }
        public double n_descuentogeneral { get; set; }
        public string cs_codlocalidad { get; set; }
        public double ns_CantidadEmpaque { get; set; }
        public double ns_cantidaddeldocumentoorigen { get; set; }
        public double n_ImpuestoPercibido { get; set; }
    }
}
