//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_COMPRAS_DESCUENTOS
    {
        public int nu_linea { get; set; }
        public double nu_montoDescuento { get; set; }
        public string cu_codigoDescuento { get; set; }
        public string cu_documento { get; set; }
        public double nu_porcentaje { get; set; }
    }
}
