//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CAMBIOS_PREMIOS
    {
        public string cs_documento { get; set; }
        public string cs_codigopremio { get; set; }
        public string cs_descripremio { get; set; }
        public double ns_valor { get; set; }
        public decimal id { get; set; }
        public string cs_tipo { get; set; }
        public int ns_cantidad { get; set; }
        public int nu_tipopremio { get; set; }
        public string CS_SUCURSAL { get; set; }
        public double ns_valorcambio { get; set; }
    }
}
