//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_COMISIONES
    {
        public string C_Codigo { get; set; }
        public string c_Tipo { get; set; }
        public decimal n_RangoMinimo { get; set; }
        public decimal n_RangoMaximo { get; set; }
        public string c_Concepto { get; set; }
        public decimal n_Porcentaje { get; set; }
        public decimal n_Monto { get; set; }
    }
}
