//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CIERRES
    {
        public string c_DOCUMENTO { get; set; }
        public System.DateTime d_FECHA { get; set; }
        public string c_CODLOCALIDAD { get; set; }
        public string c_CODMONEDA { get; set; }
        public string c_CODDENOMINA { get; set; }
        public string c_CODBANCO { get; set; }
        public double n_FACTOR { get; set; }
        public int n_CANTIDAD { get; set; }
        public double n_BOLIVARES { get; set; }
        public string c_TDC { get; set; }
        public string c_cerrado { get; set; }
    }
}
