//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Comprobantes
    {
        public decimal IDDeMovimiento { get; set; }
        public string Codigo { get; set; }
        public decimal IDDeCuenta { get; set; }
        public Nullable<short> Tipo { get; set; }
        public double Monto { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal IDDeComprobante { get; set; }
        public string USUARIO { get; set; }
        public Nullable<decimal> IDDeCentroCosto { get; set; }
    }
}
