//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CAMBIOPRECIO
    {
        public string C_DOCUMENTO { get; set; }
        public string C_CODARTICULO { get; set; }
        public double N_PRECIO1 { get; set; }
        public double N_PRECIO2 { get; set; }
        public double N_PRECIO3 { get; set; }
        public double N_COSTO { get; set; }
        public double N_OLDPRECIO1 { get; set; }
        public double N_OLDPRECIO2 { get; set; }
        public double N_OLDPRECIO3 { get; set; }
        public int N_TIPOPESO { get; set; }
        public string C_DEPARTAMENTO { get; set; }
        public string C_GRUPO { get; set; }
        public string C_SUBGRUPO { get; set; }
        public string N_PROD_EXT { get; set; }
    }
}
