//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_COSTOS_INT
    {
        public string c_des_costo { get; set; }
        public string c_des_moneda { get; set; }
        public Nullable<double> n_fac_moneda { get; set; }
        public Nullable<double> n_monto { get; set; }
        public string c_cod_costo { get; set; }
        public string c_cod_moneda { get; set; }
        public string c_gru_costo { get; set; }
        public string c_codigo { get; set; }
    }
}
