//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_DESPACHO
    {
        public string c_detalle { get; set; }
        public string c_codorden { get; set; }
        public string c_codigo { get; set; }
        public string c_descripcion { get; set; }
        public double n_cant { get; set; }
        public double n_cant_recibida { get; set; }
        public double n_cant_despachada { get; set; }
        public double n_costo { get; set; }
    }
}
