//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_DECLARACIONADM
    {
        public System.DateTime f_fecha { get; set; }
        public string c_emisor { get; set; }
        public string C_Documento { get; set; }
        public string c_concepto { get; set; }
        public double n_Monto { get; set; }
        public string C_localidad { get; set; }
        public string C_usuario { get; set; }
        public string c_Tr_Documento_Rel { get; set; }
        public decimal id { get; set; }
        public string cs_codmoneda { get; set; }
        public string CS_CODENOMINACION { get; set; }
        public string cu_codbanco { get; set; }
        public int bu_declarado { get; set; }
        public double ns_factor { get; set; }
        public Nullable<System.DateTime> DS_FECHADEPOSITADO { get; set; }
        public string cs_denominacion { get; set; }
        public string cs_moneda { get; set; }
        public string cs_emisorcuenta { get; set; }
    }
}
