//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_FACTURAS_PROGPAGOS
    {
        public string CS_CODIGO_PAGO { get; set; }
        public string CS_NUMERO_FACTURA { get; set; }
        public string CS_CONCEPTO { get; set; }
        public string CS_TIPO_FACTURA { get; set; }
        public System.DateTime DS_FECHAE { get; set; }
        public System.DateTime DS_FECHAV { get; set; }
        public double NU_MONTO_FACTURA { get; set; }
        public double NU_MONTO_CANCELADO { get; set; }
        public double NU_SALDO_FACTURA { get; set; }
        public System.DateTime DS_FECHA { get; set; }
        public double NU_MONTO_DESCUENTO { get; set; }
        public double NU_PORC_DESCUENTO { get; set; }
        public double NU_MONTO_PRONTOPAGO { get; set; }
        public double NU_PORC_PRONTOPAGO { get; set; }
        public double NU_MONTO_PRONTOPAGO2 { get; set; }
        public double NU_PORC_PRONTOPAGO2 { get; set; }
        public double NU_RETENIDOFINAL { get; set; }
        public double NU_MONTOXRETENER { get; set; }
    }
}
