//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_FORMATO_BANCOS
    {
        public string cu_codigoFormato { get; set; }
        public int nu_largo { get; set; }
        public string cu_caracterRelleno { get; set; }
        public string cu_alineacion { get; set; }
        public string cu_tipo { get; set; }
        public string cu_valor { get; set; }
        public int nu_orden { get; set; }
        public int nu_linea { get; set; }
        public string cu_posicion { get; set; }
        public string cu_separadorDecimal { get; set; }
        public string cu_formatoFecha { get; set; }
        public string cu_tipoCampo { get; set; }
        public int nu_cantidadDecimal { get; set; }
    }
}
