//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_INTERFAZ
    {
        public string cs_codigo { get; set; }
        public string cs_campo_tabla { get; set; }
        public string cs_campo { get; set; }
        public int nu_longitud { get; set; }
        public string cu_caracter_relleno { get; set; }
        public string cu_lado_relleno { get; set; }
        public string cu_separador { get; set; }
        public string cu_valor_predeterminado { get; set; }
        public string cu_caracteres_no_permitidos { get; set; }
        public int nu_posicion { get; set; }
    }
}
