//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_IMPUESTO
    {
        public string c_CODIMPUESTO { get; set; }
        public string c_DOCUMENTO { get; set; }
        public Nullable<double> n_VALOR { get; set; }
    }
}
