//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_INV_FISICO_PDT
    {
        public string cs_codigo { get; set; }
        public string cs_codigoalterno { get; set; }
        public string cs_descripcion { get; set; }
        public double ns_cantibul { get; set; }
        public double ns_costo { get; set; }
        public string cs_operador { get; set; }
        public double ns_cantidad { get; set; }
        public int ns_decimales { get; set; }
        public decimal id { get; set; }
        public string IDProceso { get; set; }
    }
}
