//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_INV_FISICO
    {
        public int c_LINEA { get; set; }
        public string c_DOCUMENTO { get; set; }
        public string c_DEPOSITO { get; set; }
        public string c_CODARTICULO { get; set; }
        public double n_CANTIDAD { get; set; }
        public double n_COSTO { get; set; }
        public double N_SUBTOTAL { get; set; }
        public decimal ID { get; set; }
        public string cs_codlocalidad { get; set; }
        public double ns_CantidadEmpaque { get; set; }
    }
}
