//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_LIBROS_CONFIGURADOS
    {
        public string CS_DOCUMENTO { get; set; }
        public string CS_CAMPOTABLA { get; set; }
        public string CS_CAMPORPT { get; set; }
        public string CS_CAMPOMOSTRAR { get; set; }
        public int NS_TIPOCAMPO { get; set; }
        public int NS_ORDEN { get; set; }
        public bool BS_TOTALIZA { get; set; }
        public bool BS_AUTOAJUSTAR { get; set; }
        public decimal NS_ANCHO { get; set; }
        public decimal ID { get; set; }
    }
}
