//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_MA_COMPARATIVO_PRECIOS
    {
        public string c_codigo { get; set; }
        public string Alias { get; set; }
        public double Precio { get; set; }
        public int Columna { get; set; }
        public int Linea { get; set; }
    }
}
