//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_OFERTAS
    {
        public string c_documento { get; set; }
        public string c_codarticulo { get; set; }
        public double n_precio1 { get; set; }
        public double n_precio2 { get; set; }
        public double n_precio3 { get; set; }
        public double n_oferta { get; set; }
        public double n_costo { get; set; }
        public int N_TIPOPESO { get; set; }
        public string C_DEPARTAMENTO { get; set; }
        public string C_GRUPO { get; set; }
        public string C_SUBGRUPO { get; set; }
        public string N_PROD_EXT { get; set; }
        public decimal ID { get; set; }
    }
}
