//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_ODC
    {
        public string c_DOCUMENTO { get; set; }
        public int c_LINEA { get; set; }
        public string c_CODARTICULO { get; set; }
        public double n_CANTIDAD { get; set; }
        public double n_COSTO { get; set; }
        public double n_subtotal { get; set; }
        public double n_impuesto { get; set; }
        public double n_total { get; set; }
        public double n_CANT_RECIBIDA { get; set; }
        public double n_porcentajeimp { get; set; }
        public double n_porcentajeimp1 { get; set; }
        public double n_porcentajeimp2 { get; set; }
        public string c_codprincipal { get; set; }
        public double n_costooriginal { get; set; }
        public double N_DESC1 { get; set; }
        public double N_DESC2 { get; set; }
        public double N_DESC3 { get; set; }
        public bool C_CAMXREP { get; set; }
        public double N_PRECIO_REP1 { get; set; }
        public double N_PRECIO_REP2 { get; set; }
        public double N_PRECIO_REP3 { get; set; }
        public double N_COSTOREP { get; set; }
        public string C_MONEDA { get; set; }
        public int N_DECIMALES { get; set; }
        public string N_PROD_EXT { get; set; }
        public string c_descripcion { get; set; }
        public double n_descuentoespecifico { get; set; }
        public double n_descuentogeneral { get; set; }
        public double ns_cantidadempaque { get; set; }
        public string cs_codlocalidad { get; set; }
        public decimal n_id { get; set; }
        public double n_ImpuestoPercibido { get; set; }
    }
}
