//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_ODC_MULTIPLE_PRODXPROV
    {
        public string codigoProducto { get; set; }
        public double cantidad { get; set; }
        public string codigoDeposito { get; set; }
        public string equipoUsar { get; set; }
    }
}
