//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEDIDOS_RUTA
    {
        public string cs_Corrida { get; set; }
        public string c_Documento { get; set; }
        public string c_Concepto { get; set; }
        public string c_CodLocalidad { get; set; }
        public System.DateTime d_Fecha { get; set; }
        public string c_Documento_Ven { get; set; }
        public double n_Subtotal { get; set; }
        public double n_Impuesto { get; set; }
        public double n_Total { get; set; }
        public string c_Documento_NDE { get; set; }
    }
}
