//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_PRODUCTOS
    {
        public string C_CODIGO { get; set; }
        public string C_DESCRI { get; set; }
        public string c_departamento { get; set; }
        public string c_grupo { get; set; }
        public string c_subgrupo { get; set; }
        public string c_marca { get; set; }
        public string c_modelo { get; set; }
        public bool c_procede { get; set; }
        public double n_costoact { get; set; }
        public double n_costoant { get; set; }
        public double n_costopro { get; set; }
        public double n_costorep { get; set; }
        public double n_precio1 { get; set; }
        public double n_precio2 { get; set; }
        public double n_precio3 { get; set; }
        public string c_seriales { get; set; }
        public string c_compuesto { get; set; }
        public string c_presenta { get; set; }
        public double n_peso { get; set; }
        public double n_volumen { get; set; }
        public double n_cantibul { get; set; }
        public double n_pesobul { get; set; }
        public double n_volbul { get; set; }
        public byte[] c_fileimagen { get; set; }
        public double n_impuesto1 { get; set; }
        public double n_impuesto2 { get; set; }
        public double n_impuesto3 { get; set; }
        public string c_cod_arancel { get; set; }
        public string c_des_arancel { get; set; }
        public double n_por_arancel { get; set; }
        public double n_costo_original { get; set; }
        public string c_observacio { get; set; }
        public int n_activo { get; set; }
        public int n_tipopeso { get; set; }
        public double n_precioO { get; set; }
        public System.DateTime f_inicial { get; set; }
        public System.DateTime f_final { get; set; }
        public Nullable<System.DateTime> h_inicial { get; set; }
        public Nullable<System.DateTime> h_final { get; set; }
        public System.DateTime add_date { get; set; }
        public System.DateTime update_date { get; set; }
        public string c_codfabricante { get; set; }
        public int HABLADOR { get; set; }
        public string C_CODMONEDA { get; set; }
        public int CANT_DECIMALES { get; set; }
        public double MONEDA_ANT { get; set; }
        public double MONEDA_ACT { get; set; }
        public double MONEDA_PRO { get; set; }
        public string N_PROD_EXT { get; set; }
        public string c_usuarioAdd { get; set; }
        public string c_usuarioupd { get; set; }
        public decimal ID { get; set; }
        public string C_CODIGO_BASE { get; set; }
        public string C_DESCRI_BASE { get; set; }
        public string TEXT1 { get; set; }
        public string TEXT2 { get; set; }
        public string TEXT3 { get; set; }
        public string TEXT4 { get; set; }
        public string TEXT5 { get; set; }
        public string TEXT6 { get; set; }
        public string TEXT7 { get; set; }
        public string TEXT8 { get; set; }
        public System.DateTime DATE1 { get; set; }
        public double NUME1 { get; set; }
        public string N_CANTIDAD_TMP { get; set; }
        public string C_COD_PLANTILLA { get; set; }
        public int NU_TIPO_PRODUCTO { get; set; }
        public int nu_insumointerno { get; set; }
        public int nu_precioregulado { get; set; }
        public double nu_pocentajemerma { get; set; }
        public int nu_nivelClave { get; set; }
        public string CU_DESCRIPCION_CORTA { get; set; }
        public bool bs_permiteteclado { get; set; }
        public bool bs_permitecantidad { get; set; }
        public double nu_stockmin { get; set; }
        public double nu_stockmax { get; set; }
    }
}
