//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_SUCURSALES
    {
        public string C_CODIGO { get; set; }
        public string C_DESCRIPCION { get; set; }
        public string C_DIRECCION { get; set; }
        public string C_GERENTE { get; set; }
        public string C_SUBGEREBTE { get; set; }
        public string C_TELEFONO { get; set; }
        public int C_ESTADO { get; set; }
        public string C_SERVIDOR { get; set; }
        public bool B_TRASMITIR { get; set; }
        public bool B_ACTVAD10 { get; set; }
        public string c_ciudad { get; set; }
        public string c_nombre_cheque { get; set; }
        public string cu_DireccionUltimaVersion { get; set; }
        public int nu_ActualizarUltimaVersion { get; set; }
        public int nu_MensajeUltimaVersion { get; set; }
        public int TIPO_CAMBIO { get; set; }
        public decimal ID { get; set; }
        public string c_Rif { get; set; }
        public string c_Grupo { get; set; }
    }
}
