//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_RETENCIONES
    {
        public string CS_RETENCION { get; set; }
        public decimal NU_CONCEPTO { get; set; }
        public int NU_ITEM_APLICAR { get; set; }
        public double NU_PORCENTAJE_APLICAR { get; set; }
        public int NU_EVENTO { get; set; }
        public bool NU_APLICAR_PROVEEDORES { get; set; }
        public int NU_NIVEL { get; set; }
        public int NU_TIPO_CAMBIO { get; set; }
        public decimal ID { get; set; }
    }
}
