//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_COMPRAS
    {
        public string C_DOCUMENTO { get; set; }
        public string C_LOCALIDAD { get; set; }
        public string C_STATUS { get; set; }
        public string C_CONCEPTO { get; set; }
        public decimal ID { get; set; }
    }
}
