//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_PRODUCTOS_GENERICOS
    {
        public decimal ID { get; set; }
        public string cCodigo { get; set; }
        public string cDescripcion { get; set; }
        public int TIPO_CAMBIO { get; set; }
        public string cNota { get; set; }
    }
}
