//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PAGO_ELECTRONICO
    {
        public int ID { get; set; }
        public string codigo { get; set; }
        public int linea { get; set; }
        public string ordenDePago { get; set; }
        public System.DateTime fechaLiberacion { get; set; }
        public string TipoPago { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public string usuario { get; set; }
        public string numeroCuenta { get; set; }
        public string Archivo { get; set; }
        public string Observacion { get; set; }
    }
}
