//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_MA_CLIENTES_CONVENIOS
    {
        public string c_codcliente { get; set; }
        public int tipo { get; set; }
        public string clave { get; set; }
        public double n_porcentaje { get; set; }
        public string ident { get; set; }
        public string descripcion { get; set; }
        public bool restringido { get; set; }
        public decimal id { get; set; }
        public int tipo_cambio { get; set; }
    }
}
