//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_DEPARTAMENTOS
    {
        public string C_CODIGO { get; set; }
        public string C_DESCRIPCIO { get; set; }
        public string C_GRUPO { get; set; }
        public string C_OBSERVACIO { get; set; }
        public decimal ID { get; set; }
        public int TIPO_CAMBIO { get; set; }
        public double NU_PORCUTILIDAD { get; set; }
        public bool B_LIBROLICORES { get; set; }
    }
}
