//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_PROVEEDORESxRETENCIONES
    {
        public string CU_PROVEEDOR { get; set; }
        public string CU_RETENCION { get; set; }
        public int CU_TIPO_CAMBIO { get; set; }
        public decimal ID { get; set; }
    }
}
