//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PRODUCCION
    {
        public string C_FORMULA { get; set; }
        public double N_CANTIDAD { get; set; }
        public double N_MERMA { get; set; }
        public string C_PRESENTA { get; set; }
        public string C_CODPRODUCTO { get; set; }
        public double N_COSTO { get; set; }
        public string C_CODMONEDA { get; set; }
        public string B_PRODUCIR { get; set; }
        public double nu_factorcosto { get; set; }
        public string cs_codlocalidad { get; set; }
    }
}
