//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_PARTES
    {
        public string c_Codigo { get; set; }
        public string c_Parte { get; set; }
        public double n_Cantidad { get; set; }
        public int TipoCambio { get; set; }
        public decimal ID { get; set; }
    }
}
