//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_TRANSPORTE
    {
        public string c_codtransporte { get; set; }
        public string c_descripcion { get; set; }
        public string c_placa { get; set; }
        public string c_color { get; set; }
        public string c_marca { get; set; }
        public string c_modelo { get; set; }
        public string c_responsable { get; set; }
        public string c_codlocalidad { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ADD_DATE { get; set; }
        public int ESTATUS { get; set; }
        public decimal ID { get; set; }
        public int TIPO_CAMBIO { get; set; }
        public double n_Peso { get; set; }
        public double n_Volumen { get; set; }
    }
}
