//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_RECEPCION_DE_DOCUMENTO
    {
        public string cu_documento { get; set; }
        public string cs_codlocalidad { get; set; }
        public System.DateTime ds_fecha { get; set; }
        public string cu_documentoRecibido { get; set; }
        public string cu_documentoRecibido_concepto { get; set; }
    }
}
