//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_REQUISICIONES
    {
        public string CS_DOCUMENTO { get; set; }
        public string CS_ESTADO { get; set; }
        public int NS_LINEA { get; set; }
        public string CS_CODARTICULO { get; set; }
        public string CS_CODIGO_PROVEEDOR { get; set; }
        public string CS_CODEDI { get; set; }
        public string CS_DESCRIPCION { get; set; }
        public double NS_CANTIDAD { get; set; }
        public double NS_COSTO { get; set; }
        public double NS_CANT_RECIBIDA { get; set; }
        public int NS_DECIMALES { get; set; }
        public string CS_CODMONEDA { get; set; }
        public double NS_FACTOR_CAMBIO { get; set; }
        public string NS_PROD_EXT { get; set; }
        public string cs_codlocalidad { get; set; }
        public double ns_CantidadEmpaque { get; set; }
    }
}
