//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_RECEPCION
    {
        public int c_LINEA { get; set; }
        public string c_CONCEPTO { get; set; }
        public string c_DOCUMENTO { get; set; }
        public string c_DEPOSITO { get; set; }
        public string c_CODARTICULO { get; set; }
        public double n_CANTIDAD { get; set; }
        public double n_COSTO { get; set; }
        public double n_SUBTOTAL { get; set; }
        public string c_TIPOMOV { get; set; }
        public double n_cant_teorica { get; set; }
        public double n_cant_diferencia { get; set; }
        public double N_IMPUESTO { get; set; }
        public double N_TOTAL { get; set; }
        public double N_PRECIO { get; set; }
        public double N_PRECIO_ORIGINAL { get; set; }
        public string STATUS { get; set; }
        public int DEC { get; set; }
        public int N_ID { get; set; }
        public decimal ID { get; set; }
        public string N_PROD_EXT { get; set; }
        public string cs_codlocalidad { get; set; }
        public double ns_CantidadEmpaque { get; set; }
        public string c_documento_origen { get; set; }
        public string c_tipodoc_origen { get; set; }
        public double ns_CantidaddelDocumentoOrigen { get; set; }
        public double n_UnidadesFactura { get; set; }
        public double n_EmpaquesFactura { get; set; }
    }
}
