//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_SOLICITUDCOMPRAS
    {
        public string c_DOCUMENTO { get; set; }
        public string c_CODARTICULO { get; set; }
        public double n_CANTIDAD { get; set; }
        public double n_COSTO { get; set; }
        public double n_subtotal { get; set; }
        public double n_porcentajeimp { get; set; }
        public double n_porcentajeimp1 { get; set; }
        public double n_porcentajeimp2 { get; set; }
        public string c_codprincipal { get; set; }
        public double n_COSTOORIGINAL { get; set; }
        public string N_PROD_EXT { get; set; }
        public decimal id { get; set; }
        public string c_descripcion { get; set; }
        public string TR_SOLICITUD { get; set; }
        public string cs_codlocalidad { get; set; }
        public double ns_CantidadEmpaque { get; set; }
        public double N_CANTIDADFAC { get; set; }
    }
}
