//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TABLAS_SYNCRONIZAR
    {
        public string CU_CODSUCURSAL { get; set; }
        public decimal cu_codtablassyncronizar { get; set; }
        public decimal id { get; set; }
    }
}
