//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TEMP_REP_HISTORICO
    {
        public string c_codarticulo { get; set; }
        public double n_cant_teorica { get; set; }
        public double n_costo { get; set; }
        public double n_total { get; set; }
        public System.DateTime f_fecha { get; set; }
        public string C_documento { get; set; }
        public string c_deposito { get; set; }
    }
}
