//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar10_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_VENTAS
    {
        public string c_DOCUMENTO { get; set; }
        public string c_CONCEPTO { get; set; }
        public string c_CODARTICULO { get; set; }
        public double n_CANTIDAD { get; set; }
        public double n_precio { get; set; }
        public double n_subtotal { get; set; }
        public double n_impuesto { get; set; }
        public double n_total { get; set; }
        public double n_CANT_VENDIDA { get; set; }
        public double N_PRECIO_ORIGINAL { get; set; }
        public decimal ID { get; set; }
        public string C_DESCRIPCION { get; set; }
        public string C_COMPUESTO { get; set; }
        public decimal codconcepto { get; set; }
        public double n_descuentogeneral { get; set; }
        public double n_descuentoespecifico { get; set; }
        public string CS_CODLOCALIDAD { get; set; }
    }
}
